config-version: 1
database:
  type: mysql
  host: localhost
  port: '3306'
  user: user
  password: ********
  database: minecraft
#Seconds
frequencyCheck: 60
ranks:
  youtuber:
    duration: 30d
    weight: 1
    displayName: '&cYoutuber'
    joinMessage:
    - '&6 ==========================================='
    - '&a Felicitaciones ya eres rango &cYoutuber&a!.'
    - '&a Gracias Por Tu Colaboracion Con El Server!'
    - '&6 ==========================================='
    leaveMessage:
    - '&6 ==========================================='
    - '&c Se ha agotado el tiempo de tu rango :('
    - '&6 ==========================================='

  vipHierro:
    duration: 30d
    weight: 1
    displayName: '&eVip Hierro'
    joinMessage:
    - '&6 ==========================================='
    - '&a Felicitaciones ya estas disfrutando de los'
    - '&a beneficios del &eVip Hierro&a!.'
    - '&a Gracias Por Tu Colaboracion Con El Server!'
    - '&6 ==========================================='
    leaveMessage:
    - '&6 ==========================================='
    - '&c Se ha agotado el tiempo de tu vip :('
    - '&6 ==========================================='
  vipDiamante:
    duration: 30d
    weight: 2
    displayName: '&bVip Diamante'
    joinMessage:
    - '&6 ==========================================='
    - '&a Felicitaciones ya estas disfrutando de los'
    - '&a beneficios del &bVip Diamante&a!.'
    - '&a Gracias Por Tu Colaboracion Con El Server!'
    - '&6 ==========================================='
    leaveMessage:
    - '&6 ==========================================='
    - '&c Se ha agotado el tiempo de tu vip :('
    - '&6 ==========================================='
  staffjr:
    displayName: '&6Staff Junior'
  staff:
    displayName: '&6Staff'
  staffJrVipHierro:
    duration: 30d
    displayName: '&6Staff Junior + &eVip Hierro'
    nextRank: staffJr
  staffJrVipDiamante:
    duration: 30d
    displayName: '&6Staff Junior + &bVip Diamante'
    nextRank: staffJr
  staffVipHierro:
    duration: 30d
    displayName: '&6Staff + &eVip Hierro'
    nextRank: staff
  staffVipDiamante:
    duration: 30d
    displayName: '&6Staff + &bVip Diamante'
    nextRank: staff


users:
  fakeuser:
    rank: vipHierro
    from: startdate
    to: enddate

