config-version: 1
database:
  type: mysql
  host: localhost
  port: '3306'
  user: user
  password: password
  database: minecraft

ranks:
  youtuber:
    duration: 30s
    weight: 1
    displayName: '&6Vip Hierro'
    joinMessage:
    - '&6 ==========================================='
    - '&a Felicitaciones ya estas disfrutando de los beneficios del Vip Diamante!.'
    - '&a Gracias Por Tu Colaboracion Con El Server!'
    - '&6 ==========================================='
    leaveMessage:
    - '&6 ==========================================='
    - '&a Se ha agotado el tiempo de tu vip :('
    - '&6 ==========================================='


  vipHierro:
    duration: 30d
    weight: 1
    displayName: '&6Vip Hierro'
  vipDiamante:
    duration: 30d
    weight: 2
    displayName: '&dVip Diamante'
users:
  fakeuser:
    rank: vipHierro
    from: startdate
    to: enddate

