config-version: 1
properties:
  # Show debug messages.
  auto-update-global: false

  # How often, in seconds, to check the chunk.
  inspection-frequency: 300
  
  # Notify players in that chunk if stuff has been culled. 
  notify-players: false

messages:
  removedEntites: "&7Removed %s %s in your chunk."