config-version: 1
database:
  type: mysql
  host: localhost
  port: '3306'
  user: user
  password: password
  database: minecraft

ranks:
  youtuber:
    duration: 30s
    weight: 1
    displayName: '&cYoutuber'
    joinMessage:
    - '&6 ==========================================='
    - '&a Felicitaciones ya eres rango &cYoutuber&a!.'
    - '&a Gracias Por Tu Colaboracion Con El Server!'
    - '&6 ==========================================='
    leaveMessage:
    - '&6 ==========================================='
    - '&c Se ha agotado el tiempo de tu rango :('
    - '&6 ==========================================='

  vipHierro:
    duration: 30s
    weight: 1
    displayName: '&eVip Hierro'
    joinMessage:
    - '&6 ==========================================='
    - '&a Felicitaciones ya estas disfrutando de los'
    - '&a beneficios del &eVip Hierro&a!.'
    - '&a Gracias Por Tu Colaboracion Con El Server!'
    - '&6 ==========================================='
    leaveMessage:
    - '&6 ==========================================='
    - '&c Se ha agotado el tiempo de tu vip :('
    - '&6 ==========================================='
  vipDiamante:
    duration: 30s
    weight: 2
    displayName: '&bVip Diamante'
    joinMessage:
    - '&6 ==========================================='
    - '&a Felicitaciones ya estas disfrutando de los'
    - '&a beneficios del &bVip Diamante&a!.'
    - '&a Gracias Por Tu Colaboracion Con El Server!'
    - '&6 ==========================================='
    leaveMessage:
    - '&6 ==========================================='
    - '&c Se ha agotado el tiempo de tu vip :('
    - '&6 ==========================================='

users:
  fakeuser:
    rank: vipHierro
    from: startdate
    to: enddate

