name: GlobalRanks
main: com.diquemc.GlobalRanks.GlobalRanks
author: Hector22x
description: Manage global ranks
version: "1.0"
depend: [DiqueMCJedis, DiqueMCUtils]
api-version: "1.15"
commands:
 setrank:
  description: Agrega el rango especificado al jugador
  usage: /setrank <playername> <rankname>
  permission: globalranks.admin
 delranks:
  description: Elimina los rangos de un jugador
  usage: /delranks <playername>
  permission: globalranks.admin
 getrank:
  description: Muestra los rangos del jugador especificado
  usage: /getrank <playername>
  permission: globalranks.admin
 rank:
  description: Muestra el rango actual.
  usage: /rank
  permission: globalranks.user
 rank check:
  description: Chequea si hay actualizaciones de ranog
  usage: /rank check
  permission: globalranks.user
 globalranks:
  description: Comando principal
  usage: /globalranks
  permission: globalranks.admin

permissions:
 globalranks.admin:
  default: op
  description: Gives access to admin commands.
 globalranks.user:
  default: true
  description: Gives access to user commands.
