name: GlobalRanks
main: com.diquemc.GlobalRanks.GlobalRanks
author: Hector22x
description: Manage global ranks
version: 0.0.1
commands:
 setrank:
  description: Agrega el rango especificado al jugador
  usage: /setrank <playername> <rankname>
  permission: globalranks.admin
 delranks:
  description: Elimina los rangos de un jugador
  usage: /delranks <playername>
  permission: globalranks.admin
 getrank:
  description: Muestra los rangos del jugador especificado
  usage: /getrank <playername>
  permission: globalranks.admin
 myrank:
  description: Muestra el rango actual.
  usage: /myrank
  permission: globalranks.admin

permissions:
 globalranks.admin:
  default: true
  description: Allows you to use the plugin.
