config-version: 1
database:
  type: mysql
  host: localhost
  port: '3306'
  user: user
  password: '********'
  database: minecraft
#Seconds
frequencyCheck: 60
ranks:
  youtuber:
    duration: 30d
    weight: 1
    displayName: '&cYoutuber'
    joinMessage:
    - '&6 ==========================================='
    - '&a Felicitaciones ya eres rango &cYoutuber&a!.'
    - '&a Gracias Por Tu Colaboracion Con El Server!'
    - '&6 ==========================================='
    leaveMessage:
    - '&6 ==========================================='
    - '&c Se ha agotado el tiempo de tu rango :('
    - '&6 ==========================================='
  vipZombie:
    duration: 5d
    weight: 1
    displayName: '&2Vip Zombie'
    joinMessage:
    - '&6 ==========================================='
    - '&a Felicitaciones ya estas disfrutando de los'
    - '&a beneficios del &2Vip Zombie&a!.'
    - '&a Gracias Por Tu Colaboracion Con El Server!'
    - '&6 ==========================================='
    leaveMessage:
    - '&6 ==========================================='
    - '&c Se ha agotado el tiempo de tu vip :('
    - '&6 ==========================================='
  vipEnderman:
    duration: 30d
    weight: 2
    displayName: '&5Vip Enderman'
    joinMessage:
    - '&6 ==========================================='
    - '&a Felicitaciones ya estas disfrutando de los'
    - '&a beneficios del &5Vip Enderman&a!.'
    - '&a Gracias Por Tu Colaboracion Con El Server!'
    - '&6 ==========================================='
    leaveMessage:
    - '&6 ==========================================='
    - '&c Se ha agotado el tiempo de tu vip :('
    - '&6 ==========================================='
  vipWither:
    duration: 40d
    weight: 2
    displayName: '&8Vip Wither'
    joinMessage:
    - '&6 ==========================================='
    - '&a Felicitaciones ya estas disfrutando de los'
    - '&a beneficios del &8Vip Wither&a!.'
    - '&a Gracias Por Tu Colaboracion Con El Server!'
    - '&6 ==========================================='
    leaveMessage:
    - '&6 ==========================================='
    - '&c Se ha agotado el tiempo de tu vip :('
    - '&6 ==========================================='
users:
  fakeuser:
    rank: vipHierro
    from: startdate
    to: enddate

